version: '3.1'

services:
  mongo:
    container_name: 7dbs_mongo_db
    image: mongo:4.0
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    container_name: 7dbs_mongo_express
    image: mongo-express:0.49
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: gonmo